### ISSUE TITLE
Update Gradle build not to include frontend when compiling Java on your local machine

### ISSUE THREAD

**Issue by linovifian** [bbortt/Buessle-App#9]
Currently when developing locally, most of the time one has to wait for the build to finish. This is rather time consuming and should be improved
- check if the build can be done incrementally, e.g. only recompiling things that have been changed
- definetly don't run prettier, linter and coverage in the normal local build

**Comment by bbortt** [comment]
It's because of the build dependencies defined in `build.gradle.kts` (backend depends on frontend):
```
withType<ProcessResources> {
        dependsOn("src:main:Buessle-Webapp:npmExport")
        from("src/main/webapp/out") {
            into("static")
        }
}
```
One needs to fully build the `React` application in order to statically move it into the final .jar file. This includes linting and testing.
On the other hand, this is clearly not needed when developing on your local machine. I'll see what I can do.
